services:
  - type: web
    name: medusa-storefront
    runtime: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MEDUSA_BACKEND_URL
        value: https://medusa-backend-*.onrender.com
      - key: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
        value: # This will need to be set manually after backend deployment
      - key: NEXT_PUBLIC_BASE_URL
        value: https://medusa-storefront-*.onrender.com
      - key: NEXT_PUBLIC_DEFAULT_REGION
        value: fr
      - key: NEXT_PUBLIC_STRIPE_KEY
        value: # Optional: Add your Stripe public key
      - key: REVALIDATE_SECRET
        generateValue: true
