services:
  - type: web
    name: medusa-storefront
    runtime: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MEDUSA_BACKEND_URL
        value: https://medusa2-0tjn.onrender.com
      - key: NEXT_PUBLIC_MEDUSA_BACKEND_URL
        value: https://medusa2-0tjn.onrender.com
      - key: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
        value: pk_0e6a8c9498dbfcbe077f15866357ad9d5e0769fdb7b04faa0cc2c20b66717930
      - key: NEXT_PUBLIC_BASE_URL
        value: https://medusa-storefront-production.onrender.com
      - key: NEXT_PUBLIC_DEFAULT_REGION
        value: fr
      - key: NEXT_PUBLIC_STRIPE_KEY
        value: # Optional: Add your Stripe public key
      - key: REVALIDATE_SECRET
        generateValue: true
