services:
  # Backend Medusa seulement pour commencer
  - type: web
    name: medusa-backend
    runtime: node
    plan: free
    rootDir: medusa-demo
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        value: http://localhost:8000
      - key: ADMIN_CORS
        value: http://localhost:9000
      - key: AUTH_CORS
        value: http://localhost:8000,http://localhost:9000
      - key: MEDUSA_ADMIN_ONBOARDING_TYPE
        value: default

databases:
  - name: medusa-db
    databaseName: medusa_production
    user: medusa_user
    plan: free
