databases:
  - name: medusa-postgres
    databaseName: medusa
    user: medusa
    plan: free

services:
  - type: web
    name: medusa-backend
    runtime: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-postgres
          property: connectionString
      - key: STORE_CORS
        value: https://medusa-storefront-*.onrender.com,http://localhost:8000
      - key: ADMIN_CORS
        value: https://medusa-backend-*.onrender.com,http://localhost:9000
      - key: AUTH_CORS
        value: https://medusa-backend-*.onrender.com,https://medusa-storefront-*.onrender.com,http://localhost:8000,http://localhost:9000
      - key: MEDUSA_ADMIN_ONBOARDING_TYPE
        value: nextjs
