services:
  - type: web
    name: medusa-backend-clean
    runtime: node
    plan: starter
    region: oregon
    buildCommand: node deploy-production.js
    startCommand: node start-production.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://medusa:OCSg5gp84TDq50NvE3Pg7wP9xm3z3FF9@dpg-d1mq3kgdl3ps73cieogg-a.oregon-postgres.render.com/medusa_jyxk?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        value: http://localhost:8000,https://medusa-storefront-clean.onrender.com,https://*.onrender.com
      - key: ADMIN_CORS
        value: http://localhost:9000,https://medusa-backend-clean.onrender.com,https://*.onrender.com
      - key: AUTH_CORS
        value: http://localhost:8000,http://localhost:9000,https://medusa-storefront-clean.onrender.com,https://medusa-backend-clean.onrender.com,https://*.onrender.com
      - key: MEDUSA_ADMIN_ONBOARDING_TYPE
        value: default
      - key: PORT
        value: 10000

  - type: web
    name: medusa-storefront-clean
    runtime: node
    plan: free
    region: oregon
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MEDUSA_BACKEND_URL
        value: https://medusa-backend-clean.onrender.com
      - key: NEXT_PUBLIC_MEDUSA_BACKEND_URL
        value: https://medusa-backend-clean.onrender.com
      - key: NEXT_PUBLIC_BASE_URL
        value: https://medusa-storefront-clean.onrender.com
      - key: NEXT_PUBLIC_DEFAULT_REGION
        value: fr
      - key: REVALIDATE_SECRET
        generateValue: true
